# GitHub Actions 发布工作流
# 在推送版本标签时自动触发,构建并发布包到 npm
name: Publish to npm

# 触发条件: 仅在推送以 v 开头的标签时触发(如 v1.0.0)
on:
  push:
    tags:
      - 'v*'

jobs:
  # npm 包发布任务
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # 使用项目主要版本
          registry-url: 'https://registry.npmjs.org'  # 设置 npm 官方源
          cache: 'npm'  # 启用 npm 依赖缓存

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 运行测试 - 确保发布前代码质量
      - name: Run tests
        run: npm test

      # 5. 构建项目 - 生成发布所需的产物
      - name: Build project
        run: npm run build

      # 6. 发布到 npm - 使用 NPM_TOKEN secret 进行认证
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}